sudo: required
services:
 - docker

before_install:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker build -t vidiganpi10/learn_docker_3 -f Dockerfile.dev .

script:
 - docker run viditgnapi10/learn_docker_3 npm run test -- --coverage

deploy:
 edge: true
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "learn_docker_3"
 env: "LearnDocker3-env"
 bucket_env: "elasticbeanstalk-us-east-2-921311410514"
 bucket_path: "learn_docker_3"
 on:
  branch: master
