sudo: required
services:
 - docker

before_install:
 - docker build -t viditganpi10/learn_docker_3 -f Dockerfile.dev .

script:
 - docker run -e CI=true viditganpi10/learn_docker_3 npm run test 

deploy:
 edge: true
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "learn_docker_3"
 env: "LearnDocker3-env"
 bucket_name: "elasticbeanstalk-us-east-2-921311410514"
 bucket_path: "learn_docker_3"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: "$AWS_SECRET_KEY"
